config/routes.rb
Rails.application.routes.draw do
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'welcome#index'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name,:duration,presence:true
end

app/models/demo1.rb
class Demo1 < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :email,:age, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :duration)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student,only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: 'Student details was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student details has been updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path , notice: 'Student has been Deleted successfully.'
  end


  private

  def student_params
    params.require(:student).permit(:name,:email,:age,:permanent_contact_number,:date_of_birth,:local_address,:permanent_address,:alternate_contact_number)
  end

  def set_student
    @student = Student.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= course.duration %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete,data: {confirm: 'Are you sure?'} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>

  <% if student.errors.any? %>
      <% student.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
  <% end %>
  <div>
    <%= form.label :name%><br>
    <%= form.text_field :name%>
  </div>
  <div>
    <%= form.label :email%><br>
    <%= form.email_field :email%>
  </div>
  <div>
    <%= form.label :age%><br>
    <%= form.text_field :age%>
  </div>
  <div>
    <%= form.label :permanent_contact_number%><br>
    <%= form.text_field :permanent_contact_number%>
  </div>
  <div>
    <%= form.label :alternate_contact_number%><br>
    <%= form.text_field :alternate_contact_number%>
  </div>
  <div>
    <%= form.label :date_of_birth%><br>
    <%= form.date_field :date_of_birth%>
  </div>
  <div>
    <%= form.label :local_address%><br>
    <%= form.text_area :local_address%>
  </div>
  <div>
    <%= form.label :permanent_address%><br>
    <%= form.text_area :permanent_address%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit student details</h1>

<%= render 'form' , student: @student%>

app/views/students/index.html.erb
<h1>Student Details</h1>

<p><%= notice %></p>

<%= link_to 'Add new details', new_student_path %><br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Permanent contact number</th>
      <th>Alternate Contact NUmber</th>
      <th>Date of Birth</th>
      <th>Local Address</th>
      <th>Permanent Address</th>

      <th>Link</th>

    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.age %></td>
        <td><%= student.permanent_contact_number %></td>
        <td><%= student.alternate_contact_number %></td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.local_address %></td>
        <td><%= student.permanent_address %></td>


        <td><%= link_to 'View',student %>  </td>
        <td><%= link_to "Edit", edit_student_path(student) %></td>
        <td><%= button_to 'Delete', student,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>This is new student page</h1>

<%= render 'form' , student: @student%>

app/views/students/show.html.erb
<h1>Show single student details</h1>

<p><%= notice %></p>

<p><strong>Name: </strong><%= @student.name %></p>
<p><strong>Email: </strong><%= @student.email %></p>
<p><strong>age: </strong><%= @student.age %></p>
<p><strong>age: </strong><%= @student.permanent_contact_number %></p>
<p><strong>age: </strong><%= @student.date_of_birth %></p>
<p><strong>age: </strong><%= @student.local_address %></p>
<p><strong>age: </strong><%= @student.permanent_address %></p>
<p><strong>age: </strong><%= @student.alternate_contact_number %></p>

<%= link_to 'Back', students_path %> <%= link_to "Edit", edit_student_path %><br>
<%= link_to 'Add new details', new_student_path %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>